#!/usr/bin/env bash
# Displays username, user id, and home directory path from /etc/passwd

while IFS=':' read -r username x userid x x homedir x
do
    echo "$username:$userid:$homedir"
done < "/etc/passwd"

