#!/usr/bin/env bash
# Displays username, user id, and home directory path from /etc/passwd

while IFS=':' read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < "/etc/passwd"

